close all;
clear;
clc;
x = [0, 3, 5, 7, 9, 11, 12, 13, 14, 15];
y = [0.0, 1.2, 1.7, 2.0, 2.1, 2.0, 1.8, 1.2, 1.0, 1.6];
x_demo = 0:0.2:16;
Y_L = interp1(x, y, x_demo, 'linear');
plot(x, y, '*', x_demo, Y_L, '-');
title('Linear');
pause;
Y_S = interp1(x, y, x_demo, 'spline');
plot(x, y, '*', x_demo, Y_S, '-');
title('spline');
pause;
plot(x_demo, Y_L, 'r-', x_demo, Y_S, 'k-');
hold on;
title('Linear & spline');
legend('Linear', 'spline');
plot(x, y, '*');
hold off;